# Generated by Django 2.2.2 on 2019-06-13 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'managed': True, 'verbose_name': 'Nome do Morador', 'verbose_name_plural': 'Moradores'},
        ),
        migrations.AlterModelTable(
            name='morador',
            table='',
        ),
    ]
