# Generated by Django 2.2.2 on 2019-06-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190613_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morador',
            old_name='Condominio',
            new_name='condominio',
        ),
    ]
